//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sucradom.LIB
{
    using System;
    using System.Collections.Generic;
    
    public partial class client
    {
        public client()
        {
            this.adresses = new HashSet<adresse>();
            this.tetecommandes = new HashSet<tetecommande>();
        }
    
        public int ID { get; set; }
        public string Nom { get; set; }
        public string Prenom { get; set; }
        public string Telephone { get; set; }
        public string Email { get; set; }
        public string MotDePasse { get; set; }
        public string IsActif { get; set; }
    
        public virtual ICollection<adresse> adresses { get; set; }
        public virtual ICollection<tetecommande> tetecommandes { get; set; }
    }
}
