//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sucradom.LIB
{
    using System;
    using System.Collections.Generic;
    
    public partial class etatcommande
    {
        public etatcommande()
        {
            this.tetecommandes = new HashSet<tetecommande>();
        }
    
        public int ID { get; set; }
        public string Nom { get; set; }
    
        public virtual ICollection<tetecommande> tetecommandes { get; set; }
    }
}
