//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sucradom.LIB
{
    using System;
    using System.Collections.Generic;
    
    public partial class lignecommande
    {
        public int FID_Commande { get; set; }
        public int FID_Produit { get; set; }
        public int Quantite { get; set; }
        public float PrixTTC { get; set; }
    
        public virtual tetecommande tetecommande { get; set; }
        public virtual produit produit { get; set; }
    }
}
