//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sucradom.LIB
{
    using System;
    using System.Collections.Generic;
    
    public partial class produit
    {
        public produit()
        {
            this.lignecommandes = new HashSet<lignecommande>();
            this.provisions = new HashSet<provision>();
        }
    
        public int ID { get; set; }
        public string Libelle { get; set; }
        public string Description { get; set; }
        public float Prix { get; set; }
        public string IsDisponible { get; set; }
        public int FID_Categorie { get; set; }
        public int FID_Image { get; set; }
        public int FID_Taxe { get; set; }
    
        public virtual categorie categorie { get; set; }
        public virtual image image { get; set; }
        public virtual ICollection<lignecommande> lignecommandes { get; set; }
        public virtual taxe taxe { get; set; }
        public virtual ICollection<provision> provisions { get; set; }
    }
}
