//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sucradom.LIB
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class sucradomEntities : DbContext
    {
        public sucradomEntities()
            : base("name=sucradomEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<adresse> adresses { get; set; }
        public DbSet<categorie> categories { get; set; }
        public DbSet<client> clients { get; set; }
        public DbSet<etatcommande> etatcommandes { get; set; }
        public DbSet<image> images { get; set; }
        public DbSet<lignecommande> lignecommandes { get; set; }
        public DbSet<produit> produits { get; set; }
        public DbSet<provision> provisions { get; set; }
        public DbSet<taxe> taxes { get; set; }
        public DbSet<tetecommande> tetecommandes { get; set; }
    }
}
