//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sucradom.LIB
{
    using System;
    using System.Collections.Generic;
    
    public partial class tetecommande
    {
        public tetecommande()
        {
            this.lignecommandes = new HashSet<lignecommande>();
        }
    
        public int ID { get; set; }
        public System.DateTime Date { get; set; }
        public float PrixTotal { get; set; }
        public int FID_Client { get; set; }
        public int FID_Etat { get; set; }
        public int FID_Adresse { get; set; }
    
        public virtual adresse adresse { get; set; }
        public virtual client client { get; set; }
        public virtual etatcommande etatcommande { get; set; }
        public virtual ICollection<lignecommande> lignecommandes { get; set; }
    }
}
